typography_spectrum: 0.1578390086069703
color:
  brandColors:
    - '#394342'
    - '#016d6c'
    - '#02888f'
    - '#299fa6'
    - '#46b4bc'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3179
analytics:
  google: null
  facebook: null
  twitter: null
name: Linux Grabs
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Linux Junk
purpose: []
