name: Linux Grabs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1578390086069703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#394342'
    - '#016d6c'
    - '#02888f'
    - '#299fa6'
    - '#46b4bc'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
