typography_spectrum: 0.31891447911038995
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.9953002985566854
  lightness: 0.3520164859946817
  saturation: 0.9240637579932809
  rhythmicContrast: 0.8446675268933177
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26025348575785756
analytics:
  google: null
  facebook: null
  twitter: null
name: Linux Grabs
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Linux Grabs
description: The Automatic Linux News Grabber
purpose: []
